### PR TITLE
[ME] Simple refactoring

### PR DESCRIPTION
**Pull request by takahiro0327**
Some code was made into a function. The main purpose is to clean up duplicated code.
There are no functional changes.
Please merge if you like.

It will make it easier to hook specific processes from the outside and should make future changes somewhat easier.
If there are changes that add functions, such as ConvertNormalMap, for example, the changes should be limited to one or two places in each Controller.

### CODE REVIEW

**Comment by takahiro0327** [comment]
Sorry, I'll make some changes, just give me a minute.

**Comment by takahiro0327** [comment]
Fixes are done.
Please review.

**Review by RikkiBalboa — APPROVED** [review]

**Comment by takahiro0327** [comment]
Thanks for the merge.
If you plan to version or release ME, give me a few days.
I think I'll put in a fix for the problem with the reset button not working if a shader not in the shader list was the initial selection.

**Comment by ManlyMarco** [comment]
@takahiro0327 Got it, thanks for letting me know. I'll probably make a release around the weekend.

**Pull request merged**
